// Shared Excel export column mapping — used by both index.html ("My HSC Reports")
// and admin.html (district Excel report). Keep this file as the single source of
// truth for the column order and Firestore-field-to-column mapping; do not fork it.

var EXCEL_HEADERS = [
  'Sl.No.',
  'Date',
  'Block',
  'PHC',
  'HWC-HSC Name',
  'Unique ID',
  'Patient Name',
  'Phone Number',
  'Age',
  'Gender',
  'Type of Patient',
  'Height',
  'Weight',
  'Type of CPHC service',
  'Type of Consultation',
  'Fever - Complaint',
  'Fever - Treatment',
  'Diarrhea - Complaint',
  'Diarrhea - Treatment',
  'Vomiting - Complaint',
  'Vomiting - Treatment',
  'Abdominal Pain - Complaint',
  'Abdominal Pain - Treatment',
  'Pain - Complaint',
  'Pain - Treatment',
  'Chest Pain - Complaint',
  'Chest Pain - Treatment',
  'Cardiac Cases managed with loading dose and referred',
  'Eye - Complaint',
  'Eye - Treatment',
  'ENT - Complaint',
  'ENT - Treatment',
  'Mental Illness',
  'Referred to Block Mental Health Psychiatrist',
  'Dog bite case attended',
  'ARV given',
  'Category 3 Referred to Higher Facility',
  'Injury/Emergency',
  'Emergency case given Inj.Td',
  'Emergency case referred to Higher Facility',
  'NCD Screening type',
  'NCD Follow up',
  'Oral Screening',
  'Oral Screening Result',
  'Breast Screening type',
  'Breast Screening Result',
  'Cervical VIA Screening',
  'Cervical Screening Result',
  'Cervical Referred to Higher Facility',
  'TB Screening',
  'TB Treatment initiated date',
  'TB Contact Screening done',
  'TB Contact Screening',
  'TB Contact Treatment initiated date',
  'Leprosy Screening',
  'Leprosy Treatment initiated date',
  'Leprosy Contact Screening done',
  'Leprosy Contact Screening',
  'Leprosy Contact Treatment initiated date',
  'Blood Pressure',
  'Temperature',
  'Pulse Rate',
  'Respiratory Rate',
  'SpO2 saturation',
  'Iodine salt test',
  'Water testing',
  'Sputum for AFB',
  'Peripheral smear for Malaria',
  'Smear for Filaria',
  'Other investigations',
  'Urine Pregnancy Test',
  'Hemoglobin value',
  'Anemia',
  'Blood Sugar value',
  'Urine Albumin',
  'Urine Sugar',
  'HIV test',
  'HbsAg',
  'VDRL',
  'Calcium Carbonate',
  'IFA Large',
  'Junior WIFS',
  'Senior WIFS',
  'Iron Syrup',
  'Co-trimoxazole',
  'T.Paracetamol',
  'T.Albendazole',
  'T.Di-cyclomine',
  'ORS',
  'HT Drugs',
  'DM Drugs',
  'Cardiac Drugs',
  'Antibiotic Drugs',
  'Other EDL drugs',
  'Family Welfare drugs',
  'AAM Portal',
  'PICME',
  'MTM',
  'HMIS',
  'IHIP'
];

var EXCEL_COLUMNS = [
  'pDate',
  'block',
  'phc',
  'hsc',
  'uniqueId',
  'pName',
  'pPhone',
  'patientAge',
  'pGender',
  'pType',
  'height',
  'weight',
  'cphcService',
  'consultType',
  'feverComplaint',
  'feverTreatment',
  'diarrheaComplaint',
  'diarrheaTreatment',
  'vomitingComplaint',
  'vomitingTreatment',
  'abdominalComplaint',
  'abdominalTreatment',
  'painComplaint',
  'painTreatment',
  'chestPainComplaint',
  'chestPainTreatment',
  'cardiacManaged',
  'eyeComplaint',
  'eyeTreatment',
  'entComplaint',
  'entTreatment',
  'mentalIllness',
  'mentalReferred',
  'dogCategory',
  'arvGiven',
  'arvCategory3Referred',
  'injuryType',
  'injTd',
  'emergencyReferred',
  'ncdScreeningType',
  'ncdFollowupDetail',
  'oralScreening',
  'oralResult',
  'breastScreening',
  'breastResult',
  'cervicalScreening',
  'cervicalResult',
  'cervicalReferred',
  'tbScreening',
  'tbTreatmentDate',
  'tbContactDone',
  'tbContactScreening',
  'tbContactTreatmentDate',
  'leprosyScreening',
  'leprosyTreatmentDate',
  'leprosyContactDone',
  'leprosyContactScreening',
  'leprosyContactTreatmentDate',
  'bp',
  'temp',
  'pulseRate',
  'respRate',
  'spo2',
  'iodineTests',
  'waterTests',
  'sputumAfb',
  'peripheralSmear',
  'smearFilaria',
  'investigationOthers',
  'upt',
  'hbValue',
  'anemia',
  'bloodSugar',
  'urineAlbumin',
  'urineSugar',
  'hiv',
  'hbsag',
  'vdrl',
  'calciumGiven',
  'ifaGiven',
  'wifsJunior',
  'wifsSenior',
  'ironSyrupGivenNew',
  'kitCotrimoxazole',
  'kitParacetamol',
  'kitAlbendazole',
  'kitDicyclomine',
  'kitOrs',
  'htDrugs',
  'dmDrugs',
  'cardiacDrugs',
  'antibioticDrugs',
  'otherEdlDrugs',
  'familyWelfare',
  'aamPortal',
  'picme',
  'mtm',
  'hmis',
  'ihip'
];

function excelVal(r, key){
  const v = r[key];
  if(v === undefined || v === null) return '';
  const s = String(v).trim();
  if(s === 'undefined' || s === 'null') return '';
  return s;
}

function rowToExcelArray(r, slNo){
  return [slNo, ...EXCEL_COLUMNS.map(col=> excelVal(r, col))];
}
