// Shared Excel export column mapping — used by both index.html ("My HSC Reports")
// and admin.html (district Excel report). Keep this file as the single source of
// truth for the column order and Firestore-field-to-column mapping; do not fork it.
// Column order matches the official HWC-HSC daily reporting format spreadsheet.

var EXCEL_HEADERS = [
  'Sl.No.',
  'Date',
  'Block',
  'PHC',
  'HWC-HSC Name',
  'Patient Name',
  'Unique ID',
  'Phone Number',
  'Age',
  'Gender',
  'Height',
  'Weight',
  'Pulse Rate',
  'Respiratory Rate',
  'Blood Pressure',
  'Temperature',
  'SpO2 level',
  'Type of CPHC service',
  'Type of Consultation',
  'Fever - Complaint',
  'Fever - Treatment',
  'Cough & Cold - Complaint',
  'Cough & Cold - Treatment',
  'Wheezing - Complaint',
  'Wheezing - Treatment',
  'Headache - Complaint',
  'Headache - Treatment',
  'Skin Lesions - Complaint',
  'Skin Lesions - Treatment',
  'Diarrhea / Dysentry - Complaint',
  'Diarrhea / Dysentry - Treatment',
  'Vomiting - Complaint',
  'Vomiting - Treatment',
  'Abdominal Pain - Complaint',
  'Abdominal Pain - Treatment',
  'Long standing Pain - Complaint',
  'Long standing Pain - Treatment',
  'Chest Pain - Complaint',
  'Chest Pain - Treatment',
  'Cardiac Cases managed with loading dose and referred',
  'Eye - Complaint',
  'Eye - Treatment',
  'ENT - Complaint',
  'ENT - Treatment',
  'Mental Illness',
  'Referred to Block Mental Health Psychiatrist',
  'Geriatric - Complaint',
  'Geriatric - Treatment',
  'Palliative - Complaint',
  'Palliative - Treatment',
  'Dog bite case attended',
  'ARV given',
  'Category 3 Referred to Higher Facility',
  'Injury/Emergency - Complaint',
  'Injury/Emergency - Treatment',
  'Emergency case given Inj.Td',
  'Emergency case referred to Higher Facility',
  'NCD Screening',
  'NCD Screening type',
  'NCD Follow up',
  'Oral Screening',
  'Oral Screening Result',
  'Breast Screening type',
  'Breast Screening Result',
  'Cervical VIA Screening',
  'Cervical Screening Result',
  'Cervical Referred to Higher Facility',
  'TB Symptoms',
  'TB Screening',
  'TB Treatment initiated date',
  'TB Contact Screening done',
  'TB Contact Screening',
  'TB Contact Treatment initiated date',
  'TB Followup',
  'Leprosy Symptoms',
  'Leprosy Screening',
  'Leprosy Treatment initiated date',
  'Leprosy Contact Screening done',
  'Leprosy Contact Screening',
  'Leprosy Contact Treatment initiated date',
  'Leprosy Followup',
  'Urine Pregnancy Test',
  'Hemoglobin value',
  'Anemia',
  'Blood Sugar value',
  'Urine Albumin',
  'Urine Sugar',
  'Visual Inspection - Acetic Acid',
  'Dengue',
  'HIV test',
  'HbsAg',
  'VDRL',
  'Iodine salt test',
  'Water testing',
  'Sputum for AFB',
  'Peripheral smear for Malaria',
  'Smear for Filaria',
  'Other investigations',
  'WHV Suspected Cases - HT',
  'WHV Suspected Cases - DM',
  'WHV Suspected Cases - Both (HT & DM)',
  'WHV Invited - Oral Screening',
  'WHV Invited - SBE/CBE Screening',
  'WHV Invited - VIA Screening',
  'Calcium Carbonate',
  'IFA Large',
  'Junior WIFS',
  'Senior WIFS',
  'Iron Syrup',
  'Co-trimoxazole',
  'T.Paracetamol',
  'T.Albendazole',
  'T.Di-cyclomine',
  'ORS',
  'HT Drugs',
  'DM Drugs',
  'Cardiac Drugs',
  'Antibiotic Drugs',
  'Other EDL drugs',
  'Family Welfare drugs',
  'AAM Portal',
  'PICME',
  'MTM',
  'HMIS',
  'IHIP'
];

var EXCEL_COLUMNS = [
  'pDate',
  'block',
  'phc',
  'hsc',
  'pName',
  'uniqueId',
  'pPhone',
  'patientAge',
  'pGender',
  'height',
  'weight',
  'pulseRate',
  'respRate',
  'bp',
  'temp',
  'spo2',
  'cphcService',
  'consultType',
  'feverComplaint',
  'feverTreatment',
  'coughColdComplaint',
  'coughColdTreatment',
  'wheezingComplaint',
  'wheezingTreatment',
  'headacheComplaint',
  'headacheTreatment',
  'skinLesionsComplaint',
  'skinLesionsTreatment',
  'diarrheaComplaint',
  'diarrheaTreatment',
  'vomitingComplaint',
  'vomitingTreatment',
  'abdominalComplaint',
  'abdominalTreatment',
  'painComplaint',
  'painTreatment',
  'chestPainComplaint',
  'chestPainTreatment',
  'cardiacManaged',
  'eyeComplaint',
  'eyeTreatment',
  'entComplaint',
  'entTreatment',
  'mentalIllness',
  'mentalReferred',
  'geriatricComplaint',
  'geriatricTreatment',
  'palliativeComplaint',
  'palliativeTreatment',
  'dogCategory',
  'arvGiven',
  'arvCategory3Referred',
  'injuryType',
  'injuryTreatment',
  'injTd',
  'emergencyReferred',
  'ncdScreening',
  'ncdScreeningType',
  'ncdFollowupDetail',
  'oralScreening',
  'oralResult',
  'breastScreening',
  'breastResult',
  'cervicalScreening',
  'cervicalResult',
  'cervicalReferred',
  'tbSymptoms',
  'tbScreening',
  'tbTreatmentDate',
  'tbContactDone',
  'tbContactScreening',
  'tbContactTreatmentDate',
  'tbFollowup',
  'leprosySymptoms',
  'leprosyScreening',
  'leprosyTreatmentDate',
  'leprosyContactDone',
  'leprosyContactScreening',
  'leprosyContactTreatmentDate',
  'leprosyFollowup',
  'upt',
  'hbValue',
  'anemia',
  'bloodSugar',
  'urineAlbumin',
  'urineSugar',
  'viaAceticAcid',
  'dengue',
  'hiv',
  'hbsag',
  'vdrl',
  'iodineTests',
  'waterTests',
  'sputumAfb',
  'peripheralSmear',
  'smearFilaria',
  'investigationOthers',
  'whvHT',
  'whvDM',
  'whvBoth',
  'whvOralScreening',
  'whvSbeCbeScreening',
  'whvViaScreening',
  'calciumGiven',
  'ifaGiven',
  'wifsJunior',
  'wifsSenior',
  'ironSyrupGivenNew',
  'kitCotrimoxazole',
  'kitParacetamol',
  'kitAlbendazole',
  'kitDicyclomine',
  'kitOrs',
  'htDrugs',
  'dmDrugs',
  'cardiacDrugs',
  'antibioticDrugs',
  'otherEdlDrugs',
  'familyWelfare',
  'aamPortal',
  'picme',
  'mtm',
  'hmis',
  'ihip'
];

function excelVal(r, key){
  const v = r[key];
  if(v === undefined || v === null) return '';
  const s = String(v).trim();
  if(s === 'undefined' || s === 'null') return '';
  return s;
}

function rowToExcelArray(r, slNo){
  return [slNo, ...EXCEL_COLUMNS.map(col=> excelVal(r, col))];
}
